"""Write docs/data.md: what the prepared datasets contain, generated from the files."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from spec_review.config import ROOT
from spec_review.data import coest, promise, reqeval

CARD = ROOT / "docs" / "data.md"


def _table(df: pd.DataFrame) -> str:
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join([str(df.index.name or ""), *cols]) + " |"]
    lines.append("|" + "---|" + "---:|" * len(cols))
    for idx, row in df.iterrows():
        cells = [f"{v:,}" if isinstance(v, int) else str(v) for v in row.tolist()]
        lines.append("| " + " | ".join([str(idx), *cells]) + " |")
    return "\n".join(lines)


def render(p: pd.DataFrame, r: pd.DataFrame, arts: pd.DataFrame, links: pd.DataFrame) -> str:
    classes = pd.crosstab(p.label.map(promise.CLASSES), p.split)[["train", "dev", "test"]]
    classes["total"] = classes.sum(axis=1)
    classes = classes.sort_values("total", ascending=False).astype(int)
    classes.index.name = "class"
    classes.columns.name = None
    projects = p.groupby("split").project.nunique().reindex(["train", "dev", "test"])
    amb = pd.crosstab(r.split, r.ambiguous.map({True: "ambiguous", False: "not ambiguous"}))
    amb.columns.name = None
    kinds = arts.groupby(["dataset", "kind"]).size().rename("artifacts").reset_index()
    kinds = kinds.set_index("dataset")
    trace = links.groupby("dataset").size().rename("links").to_frame()
    sizes = arts.groupby("dataset").size().to_dict()
    trace["density"] = [
        f"{n / max(1, sizes[str(d)]):.2f} per artifact" for d, n in trace.links.to_dict().items()
    ]
    return f"""# Data

Generated by `spec-review data-card` from the prepared files. All sources are pinned (commit or
SHA-256) in `src/spec_review/data/download.py`.

## PROMISE_exp: requirement classes

[PROMISE_exp](https://github.com/AleksandarMitrevski/se-requirements-classification) (Lima et
al. 2019), an expansion of the tera-PROMISE NFR set, CC BY-SA 3.0: **{len(p):,} requirements**
from {p.project.nunique()} projects, each labelled functional or one of eleven non-functional
classes. The split is drawn **over projects** (train {projects["train"]}, dev {projects["dev"]},
test {projects["test"]} projects), because requirements of one project share vocabulary and
templates; a random split would reward recognising the project.

{_table(classes)}

## ReqEval: ambiguous pronouns

The [NLP4RE 2020 ReqEval](https://github.com/frieden84/nlp4re-reqeval) shared task, CC BY 4.0:
{len(r)} requirements from {r.domain.nunique()} domains, each with one pronoun marked and
labelled ambiguous (readers may resolve it differently) or not, with the agreed antecedent. It
measures one kind of ambiguity only, referential ambiguity, and is used for exactly that.

{_table(amb)}

## CoEST: traceability

Datasets from the [Center of Excellence for Software and Systems Traceability](http://sarec.nd.edu/coest/datasets/)
with ground-truth trace links, used for link recovery and impact analysis (cite the original
authors listed in each dataset's readme). Source code artifacts are reduced to their identifiers
(split on camelCase), comments and strings.

{_table(kinds)}

{_table(trace)}

EasyClinic links every pair of artifact types (use cases, interaction diagrams, test cases,
code), which makes it the dataset for multi-hop impact analysis. Its documents were translated
from Italian and read accordingly; eTOUR keeps Italian identifiers in its code.
"""


def write(path: Path = CARD) -> Path:
    arts, links = coest.load()
    text = render(promise.load(), reqeval.load(), arts, links)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
